title:             Asociación Cultural Hacenderas
email:             asociacionhacenderas@gmail.com
#description:       Asociación Cultural Hacenderas
author:            hacenderas
baseurl:           ""
url:               "https://hacenderas.github.io/"

# Social Profiles
twitter_username:  hacenderas
#github_username:   grcanosa
#linkedin_username: grcanosa
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
